# Generated by Django 3.2 on 2022-04-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='update',
            new_name='updated',
        ),
    ]
