# Generated by Django 3.2 on 2022-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220429_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('blog', 'Blog'), ('jurnal', 'Jurnal'), ('technology', 'Technology'), ('programming', 'Programming')], default='blog', max_length=50),
        ),
    ]
