# Generated by Django 3.2 on 2022-05-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_author'),
        ('article', '0009_alter_article_author'),
    ]

    operations = [
    ]
